global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80
  websecure:
    address: :443
    http:
      tls:
        certResolver: idsl-resolver
    # proxyProtocol:
      # trustedIPs:
        # Cloudflare IPv4s
        # - 173.245.48.0/20
        # - 103.22.200.0/22
        # - 103.21.244.0/22
        # - 103.31.4.0/22
        # - 141.101.64.0/18
        # - 108.162.192.0/18
        # - 190.93.240.0/20
        # - 188.114.96.0/20
        # - 197.234.240.0/22
        # - 198.41.128.0/17
        # - 162.158.0.0/15
        # - 104.16.0.0/13
        # - 104.24.0.0/14
        # - 172.64.0.0/13
        # - 131.0.72.0/22
        # Cloudflare IPv6s
        # - 2400:cb00::/32
        # - 2606:4700::/32
        # - 2803:f800::/32
        # - 2405:b500::/32
        # - 2405:8100::/32
        # - 2a06:98c0::/29
        # - 2c0f:f248::/32

certificatesResolvers:
  idsl-resolver:
    acme:
      email: admin@idsl.pw
      storage: acme.idsl-pw.json
      httpChallenge:
        entryPoint: web

log:
  level: INFO
  filePath: /log/traefik.log
  format: json

accessLog:
  filePath: /log/access.log
  format: json

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true

api:
  dashboard: true
  insecure: false
